### ISSUE TITLE
Zoom-to unit, item, or location results in misaligned view

### ISSUE THREAD

**Issue by Stathol** [mifki/df-twbt#41]
Zooming to units, items, or locations from most menus will center the view on a point far to the left of the intended target. The cursor will be correctly positioned over the target, but the target and cursor will be offscreen or obscured by the menu. I suspect this can happen from any zoom-to feature, but I've only personally confirmed the behavior from the units screen, announcements menu, combat reports, and the enhanced stocks menu (part of dfhack, I believe).

It seems that zoom level plays some role in this. At particular zoom levels, Urist McMiner can be reliably zoomed-to from anywhere, while Ral McHauler cannot. Change your zoom level, and the situation may be reversed (or neither or both will be broken).

Another possibly useful data point: zoom-to seems to always work correctly (regardless of zoom level) if the target falls within the current view window, or would fall within the current view window if it were moved strictly up/down to the target's z-level. This holds true even if the window is ultimately nudged to recenter on the unit.

Pause-on-announce exhibits the same behavior, but I see that's listed as a separate issue (#31) .

According to #16, zoom-to was already fixed as of 5.47, but I'm using 5.58 from PeridexisErrant/LNP 0.42.06-r02. Having not used 5.47-5.57 myself, I don't know whether this is regression behavior, or if the previous zoom-to fix was partial.

**Comment by pronvit** [comment]
This should be fixed in 5.59. However, zooming is fixed for each screen (on which you can press a key to zoom), so there are likely more screens not covered yet. Tell me if you notice incorrect zooming behaviour somewhere.

**Comment by ValNyz** [comment]
Hi,

I've got this trouble too. I use the LNP package available from the AUR on a Surface Pro 3 (2160 x 1440). So the TWBT version is the last one i think.
I agree that i've got no problem with TWBT-legacy.

**Comment by lethosor** [comment]
What screens are you seeing the problem on?

**Comment by changemewtf** [comment]
I'm getting this issue using GemSet (24x24) on the [Lazy Mac Pack alpha](http://dffd.bay12games.com/file.php?id=12202) using [this preview build](https://github.com/thurin/df-twbt/releases/tag/0.47.03-alpha0-200218004) of TWBT. It's happening consistently when using the "zoom to" feature on the Units screen and when assigning stockpile give/takes. I tried disabling `mousequery` like @ValNyz suggested, and it actually seems to have fixed things up! Now I can figure out who's stealing my artifacts...

**Comment by nornagon** [comment]
FWIW I still have this issue even when disabling mousequery.
